config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }
  has_many :categories, through: :article_categories
  has_many :article_categories
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]+\z/, message: "only allows letters and numbers" }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase } 
  has_many :articles, dependent: :destroy
  validates :username, presence: true, length: { minimum: 3, maximum: 50 }, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]+\z/, message: "only allows letters and numbers" }
  validates :password, presence: true, length: { minimum: 6, maximum: 50 }, confirmation: true
  validates :email, presence: true, length: { minimum: 3, maximum: 50 }, uniqueness: { case_sensitive: false }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "must be a valid email address" }
  has_secure_password  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :logged_in?

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform this action"
      redirect_to root_path
    end
  end

  def is_admin?
    if !current_user.admin?
      flash[:danger] = "You must be an admin to perform this action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params) 
      flash[:notice] = "Article was successfully updated"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:show, :index]

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    @categories = Category.all
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new

end

def create
  user = User.find_by(email: params[:session][:email].downcase)
  if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:success] = "You have successfully logged in"
    redirect_to user_path(user)
  else
    flash.now[:danger] = "There was something wrong with your login information"
    render 'new'
  end
end

def destroy
  session[:user_id] = nil
  flash[:success] = "You have logged out"
  redirect_to root_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User was successfully created"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = "User was successfully deleted"
    redirect_to users_path
  end


  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You can only edit or delete your own profile"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.username)
  end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>

  <h2>Errors</h2>
  <ul>
    <% @article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @article, data: { turbo: false }, local:true)  do |f| %>
  <%= f.label :title %>
  <br>
  <%= text_field :article, :title %>
  <br>
    <%= f.label :description %>
    <br>
  <%= text_area :article, :description %>
  <br>
  <%= submit_tag "Submit" %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= render 'form' %>

Go back to <%= link_to 'articles', articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>
<%= will_paginate @articles %>
<table>
<thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th colspan='3'>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <% if article.user  %>
        by <%= link_to article.user.username, user_path(article.user) %>
      <% end %>
      <td><%= link_to 'Show', article_path(article) %></td>
      <% if logged_in? && current_user == article.user %>
      <td><%= link_to 'Edit', edit_article_path(article), data: { "turbo-method": :edit } %></td>
      <td><%= link_to "Delete", article_path(article), data: { "turbo-method": :delete, "turbo-confirm": "are you sure?" } %> </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @articles %>
<p>
<%= link_to 'Create New Article', new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>
<%= render 'form' %>

Go back to <%= link_to 'articles', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<h3><%= @article.title %></h3>
<p><%= @article.description%></p>
<% if @article.user %>
by <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
<% end %>
<%= link_to 'Edit', edit_article_path(@article) %> | 
<%= link_to 'Back', articles_path %> |
<%= link_to 'Delete', article_path(@article), data: { "turbo-method": :delete, "turbo-confirm": "are you sure?" } %>

app/views/categories/_form.html.erb
<% if @category.errors.any? %>

  <h2>Errors</h2>
  <ul>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @category, data: { turbo: false }, local:true)  do |f| %>
    <%= f.label :name %>
    <br>
  <%= text_field :category, :name %>
  <%= submit_tag "Submit" %>
<% end %>

app/views/categories/index.html.erb
<h1>List of category</h1>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>

app/views/categories/new.html.erb
<h1>Create a category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Category</h1>
<%= @category.name %>

app/views/layouts/_message.html.erb
    <% flash.each do |name, message| %>
      <%= content_tag :div, message, class: name %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/message' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is my about page </h1>

app/views/pages/home.html.erb
<h1>This is my homepage</h1>
<%= link_to "Sign up!", signup_path %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>

  <h2>Errors</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @user, data: { turbo: false }, local:true)  do |f| %>
  <%= f.label :username %>
  <br>
  <%= text_field :user, :username %>
  <br>
    <%= f.label :email %>
    <br>
  <%= email_field :user, :email %>
  <br>
      <%= f.label :password %>
    <br>
  <%= password_field :user, :password %>
  <br>
  <%= submit_tag "Submit" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/users/index.html.erb
Users
<%= will_paginate @users %>
<% @users.each do |user| %>
  <%= link_to user.username, user_path(user) %>
  <%= link_to gravatar_for(user, size: 150), user %>
<% end %>
<%= will_paginate @users %>

app/views/users/new.html.erb
<h1>sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<%= @user.username %>'s profile

<%= gravatar_for @user %>

<%= link_to "Edit", edit_user_path(@user) %>
Articles
<%= will_paginate @articles %>
<% @user.articles.each do |article| %>
  <%= link_to article.title, article_path(article) %>
<% end %>
<%= will_paginate @articles %>

app/views/users/update.html.erb
<h1>Edit</h1>
<%= render 'form' %>